-- ============================================================================
-- Muse — Postgres schema
-- ============================================================================
--
-- Port of schema.sql for Postgres 14+. Picked at install time by
-- `_migration_001_initial` when the configured dialect is postgres.
--
-- Differences from the SQLite schema (and why):
--
--   * INTEGER PRIMARY KEY AUTOINCREMENT  →  INTEGER GENERATED BY DEFAULT
--     AS IDENTITY PRIMARY KEY. SQLite's rowid magic has no Postgres
--     equivalent; IDENTITY is the SQL-standard replacement.
--
--   * Epoch-seconds columns  →  BIGINT. Postgres INTEGER is strictly
--     32-bit and would overflow in 2038. SQLite's INTEGER is variable-
--     width so the same column declaration works there.
--
--   * Case-insensitive text  →  CITEXT (requires the citext extension,
--     enabled at the top of this file). CITEXT compares =, <>, LIKE
--     case-insensitively at the storage layer, which replaces every
--     `COLLATE NOCASE` clause in queries.py. The connection wrapper
--     strips those clauses out before handing SQL to psycopg.
--
--   * No PRAGMAs — Postgres tunes via postgresql.conf / ALTER SYSTEM,
--     not per-connection. Deployment notes live in docker-compose.yml.
--
--   * FTS5 virtual table + triggers  →  tsvector column on tracks +
--     GIN index + trigger function. Same logical model (denormalized
--     artist_name / album_name maintained on track write), but the
--     ranking model is `ts_rank` instead of FTS5 BM25 and the query
--     uses `@@ websearch_to_tsquery(...)` instead of `MATCH ...`.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS citext;

-- ---------------------------------------------------------------------------
-- schema_version: one-row table tracking the most-recently-applied migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY
);

-- ---------------------------------------------------------------------------
-- music_folders: each row is a root directory the scanner walks.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS music_folders (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    path TEXT NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- artists
-- We deduplicate by lower-cased name. "The Beatles" and "the beatles" are
-- the same artist. Display name keeps original casing — stored as CITEXT
-- so sort/compare ignore case without explicit COLLATE clauses.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS artists (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            CITEXT NOT NULL,
    name_lower      TEXT NOT NULL UNIQUE,        -- dedup key, lowercased in app code
    sort_name       CITEXT,                       -- "Beatles, The" for sorting
    album_count     INTEGER NOT NULL DEFAULT 0,   -- denormalized for fast browse
    image_id        TEXT,                         -- artwork cache hash (Deezer-sourced)
    musicbrainz_id  TEXT                          -- MBID, optional, from tags
);
CREATE INDEX IF NOT EXISTS idx_artists_sort      ON artists(sort_name);
CREATE INDEX IF NOT EXISTS idx_artists_name_low  ON artists(name_lower);

-- ---------------------------------------------------------------------------
-- albums
-- An album is keyed by (artist_id, name_lower). Compilations get artist_id
-- pointing at the "Various Artists" sentinel artist (created on demand).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS albums (
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id                       INTEGER NOT NULL,
    name                            CITEXT NOT NULL,
    name_lower                      TEXT NOT NULL,
    sort_name                       CITEXT,              -- name with leading punct/articles stripped
    year                            INTEGER,
    genre                           CITEXT,
    release_type                    TEXT,                -- MusicBrainz primary type: album/ep/single/...
    track_count                     INTEGER NOT NULL DEFAULT 0,
    duration                        INTEGER NOT NULL DEFAULT 0,  -- total seconds
    cover_art_id                    TEXT,                -- file hash of the artwork blob
    created_at                      BIGINT NOT NULL,     -- unix epoch — Subsonic "created"
    musicbrainz_id                  TEXT,                -- release MBID
    musicbrainz_releasegroup_id     TEXT,                -- release-group MBID (cross-edition)
    FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE,
    UNIQUE (artist_id, name_lower)
);
CREATE INDEX IF NOT EXISTS idx_albums_artist        ON albums(artist_id);
CREATE INDEX IF NOT EXISTS idx_albums_year          ON albums(year);
CREATE INDEX IF NOT EXISTS idx_albums_genre         ON albums(genre);
CREATE INDEX IF NOT EXISTS idx_albums_created       ON albums(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_albums_name          ON albums(name);
CREATE INDEX IF NOT EXISTS idx_albums_sort          ON albums(sort_name);
CREATE INDEX IF NOT EXISTS idx_albums_release_type  ON albums(release_type);
-- Composite that lets the artist-index cover-art lookup hit a single index
-- without touching the table rows.
CREATE INDEX IF NOT EXISTS idx_albums_artist_year   ON albums(artist_id, year DESC, created_at DESC);

-- ---------------------------------------------------------------------------
-- tracks
-- One row per audio file on disk.
--
-- search_tsv: denormalized full-text index column maintained by the trigger
-- below. Replaces the FTS5 virtual table from the SQLite schema. Stored on
-- the table itself (not a side table) because GIN indexes work fine on a
-- regular column and one less table means one less trigger to maintain.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tracks (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id        INTEGER,                    -- nullable: stray files allowed
    artist_id       INTEGER,                    -- track artist (may differ from album artist)
    music_folder_id INTEGER NOT NULL,
    path            TEXT NOT NULL UNIQUE,       -- absolute path (UNIQUE provides the index)
    title           CITEXT NOT NULL,
    track_number    INTEGER,
    disc_number     INTEGER,
    duration        INTEGER,                    -- seconds
    bitrate         INTEGER,                    -- kbps
    size            BIGINT NOT NULL,            -- bytes (BIGINT — flac files can exceed 2GiB)
    suffix          TEXT NOT NULL,              -- "mp3", "flac", ...
    content_type    TEXT NOT NULL,              -- "audio/mpeg", ...
    year            INTEGER,
    genre           CITEXT,
    -- Scan bookkeeping
    mtime           BIGINT NOT NULL,            -- file mtime (epoch seconds)
    content_hash    TEXT,                       -- partial hash; populated by future enrichment
    last_scanned    BIGINT NOT NULL,            -- epoch seconds
    musicbrainz_id  TEXT,                       -- recording MBID
    search_tsv      tsvector,                   -- full-text index, maintained by trigger
    FOREIGN KEY (album_id)        REFERENCES albums(id)        ON DELETE SET NULL,
    FOREIGN KEY (artist_id)       REFERENCES artists(id)       ON DELETE SET NULL,
    FOREIGN KEY (music_folder_id) REFERENCES music_folders(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tracks_album   ON tracks(album_id, disc_number, track_number);
CREATE INDEX IF NOT EXISTS idx_tracks_artist  ON tracks(artist_id);
CREATE INDEX IF NOT EXISTS idx_tracks_folder  ON tracks(music_folder_id);
CREATE INDEX IF NOT EXISTS idx_tracks_title   ON tracks(title);
CREATE INDEX IF NOT EXISTS idx_tracks_year    ON tracks(year);
-- Partial index — most rows have a non-NULL genre, so we skip the NULLs
-- and the index is roughly half the size. Identical syntax to the SQLite
-- definition; Postgres supports partial indexes natively.
CREATE INDEX IF NOT EXISTS idx_tracks_genre
    ON tracks(genre) WHERE genre IS NOT NULL;
-- Recording MBID lookup — used when importing external playlists
-- (ListenBrainz) where each track is matched by its MusicBrainz id first.
CREATE INDEX IF NOT EXISTS idx_tracks_musicbrainz_id
    ON tracks(musicbrainz_id) WHERE musicbrainz_id IS NOT NULL;
-- GIN index on the search vector — the right structure for tsvector @@ tsquery.
CREATE INDEX IF NOT EXISTS idx_tracks_search_tsv ON tracks USING GIN (search_tsv);

-- ---------------------------------------------------------------------------
-- users
-- Includes all the Subsonic / OpenSubsonic role + preference columns.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                 CITEXT NOT NULL UNIQUE,
    password_hash            TEXT NOT NULL,
    is_admin                 INTEGER NOT NULL DEFAULT 0,
    created_at               BIGINT NOT NULL,
    password_changed_at      BIGINT,
    disabled                 INTEGER NOT NULL DEFAULT 0,
    -- Encrypted plaintext for Subsonic token+salt auth across restarts.
    encrypted_password       TEXT,
    -- Profile fields
    email                    TEXT,
    scrobbling_enabled       INTEGER NOT NULL DEFAULT 0,
    max_bit_rate             INTEGER NOT NULL DEFAULT 0,
    -- Subsonic 1.16.1 roles — defaults follow the spec: stream/settings/
    -- playlist are true for normal users, everything else admin-gated.
    settings_role            INTEGER NOT NULL DEFAULT 1,
    stream_role              INTEGER NOT NULL DEFAULT 1,
    download_role            INTEGER NOT NULL DEFAULT 0,
    upload_role              INTEGER NOT NULL DEFAULT 0,
    playlist_role            INTEGER NOT NULL DEFAULT 1,
    cover_art_role           INTEGER NOT NULL DEFAULT 0,
    comment_role             INTEGER NOT NULL DEFAULT 0,
    podcast_role             INTEGER NOT NULL DEFAULT 0,
    jukebox_role             INTEGER NOT NULL DEFAULT 0,
    share_role               INTEGER NOT NULL DEFAULT 0,
    video_conversion_role    INTEGER NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- starred / favorites.
-- One row per (user, target). target_type ∈ ('track','album','artist').
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS starred (
    user_id     INTEGER NOT NULL,
    target_type TEXT NOT NULL,
    target_id   INTEGER NOT NULL,
    starred_at  BIGINT NOT NULL,
    PRIMARY KEY (user_id, target_type, target_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- Composite supports "get this user's stars newest-first" without a temp sort.
CREATE INDEX IF NOT EXISTS idx_starred_user_at ON starred(user_id, starred_at DESC);

-- ---------------------------------------------------------------------------
-- playlists
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS playlists (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   INTEGER NOT NULL,
    name       TEXT NOT NULL,
    comment    TEXT,
    is_public  INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS playlist_tracks (
    playlist_id INTEGER NOT NULL,
    position    INTEGER NOT NULL,
    track_id    INTEGER NOT NULL,
    PRIMARY KEY (playlist_id, position),
    FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
    FOREIGN KEY (track_id)    REFERENCES tracks(id)    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_pltracks_track ON playlist_tracks(track_id);

-- ---------------------------------------------------------------------------
-- play_counts / scrobble.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS play_counts (
    user_id     INTEGER NOT NULL,
    track_id    INTEGER NOT NULL,
    play_count  INTEGER NOT NULL DEFAULT 0,
    last_played BIGINT,
    PRIMARY KEY (user_id, track_id),
    FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
    FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE
);
-- frequent/recent album sort joins play_counts on track_id; without this
-- Postgres would do a hash join on the full table every call.
CREATE INDEX IF NOT EXISTS idx_play_counts_track ON play_counts(track_id);

-- ---------------------------------------------------------------------------
-- play_queues / play_queue_entries (Subsonic savePlayQueue / getPlayQueue).
-- One header row per user; child table holds the ordered list of track ids.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS play_queues (
    user_id      INTEGER PRIMARY KEY,
    current_id   INTEGER,
    position_ms  INTEGER NOT NULL DEFAULT 0,
    changed_at   BIGINT NOT NULL,
    changed_by   TEXT NOT NULL,
    FOREIGN KEY (user_id)    REFERENCES users(id)  ON DELETE CASCADE,
    FOREIGN KEY (current_id) REFERENCES tracks(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS play_queue_entries (
    user_id  INTEGER NOT NULL,
    position INTEGER NOT NULL,
    track_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, position),
    FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
    FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Full-text search: tsvector column on tracks + GIN index + trigger.
--
-- The trigger denormalizes artist_name and album_name onto the track row
-- the same way the SQLite FTS5 triggers do, so search3 can match across
-- (title, artist_name, album_name, genre) with a single query. Weights
-- (A/B/C/D) drive ts_rank ordering — title hits rank highest.
--
-- Limitation: if an artist or album is renamed, the tracks' tsvectors
-- don't update automatically. We never rename artists/albums today —
-- upsert_artist / upsert_album only update sort_name + image_id on
-- conflict — so this is a non-issue in practice. If we ever add a
-- rename feature, add an AFTER UPDATE trigger on artists/albums that
-- updates the dependent tracks.search_tsv.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION tracks_search_tsv_update() RETURNS TRIGGER AS $$
DECLARE
    art_name TEXT;
    alb_name TEXT;
BEGIN
    -- Resolve denormalized names from the parent rows. NULL artist/album
    -- ids (stray tracks) just produce empty contributions to the vector.
    IF NEW.artist_id IS NOT NULL THEN
        SELECT name::TEXT INTO art_name FROM artists WHERE id = NEW.artist_id;
    END IF;
    IF NEW.album_id IS NOT NULL THEN
        SELECT name::TEXT INTO alb_name FROM albums  WHERE id = NEW.album_id;
    END IF;

    NEW.search_tsv :=
        setweight(to_tsvector('simple', COALESCE(NEW.title::TEXT, '')), 'A') ||
        setweight(to_tsvector('simple', COALESCE(art_name,         '')), 'B') ||
        setweight(to_tsvector('simple', COALESCE(alb_name,         '')), 'C') ||
        setweight(to_tsvector('simple', COALESCE(NEW.genre::TEXT, '')), 'D');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tracks_search_tsv_insert ON tracks;
CREATE TRIGGER tracks_search_tsv_insert
    BEFORE INSERT ON tracks
    FOR EACH ROW EXECUTE FUNCTION tracks_search_tsv_update();

DROP TRIGGER IF EXISTS tracks_search_tsv_update ON tracks;
CREATE TRIGGER tracks_search_tsv_update
    BEFORE UPDATE ON tracks
    FOR EACH ROW EXECUTE FUNCTION tracks_search_tsv_update();
